### ISSUE TITLE
Sotw entry validations

### ISSUE THREAD

**Issue by Robin-M** [Haamcdevs/haamcbot#50]
- [ ] The following entry (equal to the template) is accepted:

artist: 
title: 
anime:
url:

I think the field values (after the colon) should match 0 or more spaces followed by at least 1 non-space character. So if someone forgets to fill in one field the entry is rejected.

- [x] Illegal streaming sites are accepted. Only youtube.com and youtu.be should be allowed.

- [x] Nice to have: search the artist and title in the list of winners. If a full match is found, reject the entry. Of course this will not prevent _all_ duplicates because of spelling or name order, but most of us probably just copy the values from MAL anyway.

**Comment by ihulsbus** [comment]
Additionally we need to make sure the SOTW code also forces the rules of the STOW. I'll create an new issue for this
