### ISSUE TITLE
Sotw disable write after 10th song

### ISSUE THREAD

**Issue by Robin-M** [Haamcdevs/haamcbot#51]
Sotw has a limit of 10 songs per week to keep it exciting and to prevent listeners from having to listen to many songs. So after the 10th song is approved the channel should no longer allow new entries by disabling write permission for everyone. I think the old bot used to do this.

Note: if the 10th song is rejected, the channel should keep open, of course.

**Comment by janvernieuwe** [comment]
The contest is not popular enough for this feature right now.
If some day it becomes too much, we'll do it then.

It was a conscious decision we made while developing to not implement the limit.
